### PR TITLE
Update dawn to a recent version

### PR DESCRIPTION
**Pull request by edevil**
This makes the code compile with a recent Dawn version, but I wonder if additional changes are needed since I don't see anything drawn on the window the server process pops up.

Also, when I terminate the client, the server process crashes with a segfault. :)

### CODE REVIEW

**Comment by rsms** [comment]
I've updated dawn in other (non OSS) projects lately and quite a lot of little things changed.

Before landing this PR, I'm going to ask that you please test & make sure it works correctly (as in draws stuff, window resizing working etc) on Linux Ubuntu and macOS 10.15

**Comment by edevil** [comment]
The only thing it does is paint the window pink, and doesn't seem to draw anything more, at least I don't see changes. But since I never saw the original working I don't really know what I should expect. :)

**Comment by rsms** [comment]
It just draws a triangle. See: https://github.com/rsms/dawn-wire-example/blob/e0c57fe2c6a0b330d5a41717ae8d4d8904773479/client.cc#L190

Now, that shader will likely not compile in modern Dawn since WGSL hadn't stabilized two years ago.

**Comment by edevil** [comment]
Wouldn't we get some kind of error in that case? Nothing seems to fail, at least there's no error output.

**Pull request closed without merging**
